languageCode:           "en"
title:                  "Valkyrie"
baseURL:                "https://sippy-platform.github.io/valkyrie"
enableInlineShortcodes: true
enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "term", "RSS"]

publishDir:             "_site"

security:
  enableInlineShortcodes: true
  funcs:
    getenv:
      - ^HUGO_

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false

module:
  mounts:
    - source:           docs/assets
      target:           assets
    - source:           docs/content
      target:           content
    - source:           docs/data
      target:           data
    - source:           docs/layouts
      target:           layouts
    - source:           docs/static
      target:           static
    - source:           docs/static/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           docs/static/assets/img/favicons/favicon.png
      target:           static/favicon.png
    - source:           valkyrie.svg
      target:           static/valkyrie.svg
    - source:           icons
      target:           static/assets/icons
    - source:           font
      target:           static/assets/font
    - source:           node_modules/bootstrap/scss
      target:           assets/scss/bootstrap
    - source:           node_modules/bootstrap/dist/js/bootstrap.min.js
      target:           assets/js/bootstrap.min.js

params:
  description:          "Open source SVG icon library from Sippy"
  social_image_path:    /assets/img/valkyrie-social.png

  version:              "0.21.1"

  main:                 "https://sippy.cloud"
  github_org:           "https://github.com/sippy-platform"
  repo:                 "https://github.com/sippy-platform/valkyrie"
  icons_figma:          "https://www.figma.com/community/file/1164522380895285426"
