name: Deploy to GitHub Pages

on:
  push:
    branches: ['1.0']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Production build
        run: npm run prod
      - name: Install dependencies
        working-directory: docs
        run: npm install
      - name: Build
        working-directory: docs
        run: npm run build
      - name: Setup Pages
        working-directory: docs
        uses: actions/configure-pages@v3
      - name: Upload artifact
        working-directory: docs
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        working-directory: docs
        id: deployment
        uses: actions/deploy-pages@v1
